config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :members

  def params_valid?
    return false  unless contact_params[:email] =~ /.+@.+/
    return false unless contact_params[:phone] =~ /[\d\-\(\)\s]+/
    true
  end

  def members
    @projects = [
      { name: "SISCAT", photo: "siscat", dialog: "siscat" },
      { name: "Amapá Shipping", photo: "amapashipping", dialog: "amapashipping" },
      { name: "uRadiu", photo: "uRadiu", dialog: "uradiu" },
      { name: "GSAN", photo: "gsan", dialog: "gsan" },
      { name: "Sistema de Atendimento", photo: "cooperativataxi", dialog: "cooperativataxi" },
      { name: "Controle de Certificados", photo: "certifica", dialog: "certifica" },
      { name: "Controle de Produção", photo: "senai-producao", dialog: "senaiproducao" },
    ]

    @members = [
      { name: "Joelma Gonçalves", photo: "joelma", job: "Gerente de Projetos", linkedin: "in/joelma-gonçalves-fernandes-08631347", twitter: "joelmag33331053", facebook: "joelma.goncalves.921" },
      { name: "Paulo Igor", photo: "pigor", job: "Engenheiro de Software", linkedin: "in/pigodinho/pt", twitter: "pigodinho", facebook: "pigodinho"},
      { name: "Jaco Júnior", photo: "junior", job: "Analista de Negócio", linkedin: "pub/jaco-j%C3%BAnior/86/620/372", facebook: "jaco.junior1"},
      { name: "Pamela Gatinho", photo: "pamela", job: "Engenheira de Software", linkedin: "pub/pamela-gatinho/19/444/991/pt", twitter: "pamelagatinho", facebook: "pamela.gatinho"},
      { name: "Felipe Santos", photo: "felipe", job: "Engenheiro de Software", linkedin: "pub/felipe-santos-marques/40/89a/546", facebook: "felipesantos2089"},
      { name: "Matheus Souza", photo: "matheus", job: "Engenheiro de Software", linkedin: "pub/matheus-souza/38/38b/186", facebook: "matheusouza"},
      { name: "Luiz Sanches", photo: "sanches", job: "Engenheiro de Software", linkedin: "in/luizgrsanches/pt", twitter: "luizsanxes", facebook: "luizgrsanches"},
      { name: "Ricardo Casseb", photo: "casseb", job: "Engenheiro de Software", linkedin: "pub/ricardo-casseb/19/524/534/pt", twitter: "rcasseb", facebook: "ricardocasseb"},
      { name: "Ewertton Bravo", photo: "ewertton", job: "Engenheiro de Software", linkedin: "in/ewertton-bravo-03b98641", twitter: "ewerttonbravo"},
      { name: "Rafaela Lobo", photo: "rafaela", job: "DBA", linkedin: "in/rafaelaslobo", twitter: "rafaelaslb", facebook: "rafaelaslobo"}
    ]
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    if params_valid?
      Contacts.contact_message(contact_params).deliver
      respond_to do |format|
        format.json  { render :json => {text: "Mensagem enviada com sucesso!", response: "success"} }
      end
    else
      respond_to do |format|
        format.json  { render :json => {text: "Error ao enviar a mensage, por favor outra hora!", response: "success"} }
      end
    end
  end

  private

  def contact_params
    params.permit(:name, :email, :phone, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/contact_message.html.erb
<h3>Contato pelo Site</h3>

<p>Nome: <%= @name %></p>
<p>Email: <%= @email %></p>
<p>Telefone: <%= @phone %></p>
<p>
  <%= @message %>
</p>

app/views/contacts/contact_message.txt.erb
Contato pelo Site

Nome: <%= @name %>
Email: <%= @email %>
Telefone: <%= @phone %>

Mensagem: <%= @message %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pródiga Sistemas</title>
  <link rel="stylesheet"  href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="index" data-spy="scroll" data-target=".navbar-inner">

<%= yield %>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/_amapashipping.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Amapá Shipping</h4>
    </div>
    <div class="modal-body">
      <p>Hot Site da Empresa Amapá Shipping que presta os serviços de Suporte Portuário, Agenciamento de Navios, Operações de Portos e Abastecimento de Navios.</p>
      <p><a href="http://www.amapashipping.com.br" target="_blank" class="btn btn-default">Site Amapá Shipping</a></p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>

</div> 

app/views/pages/_certifica.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Controle de Certificados</h4>
    </div>
    <div class="modal-body">
      <p>
      O sistema de Controle de Certificados do SENAI (Pará) é um sistema que ajuda a acompanhar, gerenciar e controlar todo o fluxo de liberação, produção e entrega dos certificados.
      <br/>
      A visão desse produto era poder de maneira rápida e fácil acompanhar todo esse processo para eliminar desperdícios e minimizar erros durante todo o ciclo de emissão e entrega dos certificados, e ainda melhorar a segurança para todos os alunos dos cursos do SENAI no Pará.
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>

</div>

app/views/pages/_clients.html.erb
<div class="container-out container-dark" id="clients">

  <div class="title title-section">
    <h2>Nossos Clientes</h2>
    <span class="sticker">
      <i class="icon icomoon-quill"></i>
    </span>
  </div><!-- .title.title-section -->

</div><!-- .container-out -->

<div class="container-out container-full-width">

  <div class="grid-wrap">
    <section id="portfolio" class="grid" data-columns="4">
      <article class="project project-animated illustration design">
        <div class="project-heading">
          <div class="thumbnail">
            <img src="/assets/marinha.jpg" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Marinha</h2>
            <p class="desc"></p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article><!-- .project -->

      <article class="project project-animated illustration photography">
        <div class="project-heading">
          <div class="thumbnail">
            <img src="/assets/zerbini.jpg" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Fundação Zerbini</h2>
            <p class="desc"></p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article><!-- .project -->

      <article class="project project-animated illustration animation">
        <div class="project-heading">
          <div class="thumbnail">
            <img src="/assets/foton.png" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Fóton Informática</h2>
            <p class="desc"></p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article><!-- .project -->

      <article class="project project-animated animation web">
        <div class="project-heading">
          <div class="thumbnail">
            <img src="/assets/logoprodepa.png" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">PRODEPA</h2>
            <p class="desc">Fóton</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article><!-- .project -->

      <article class="project project-animated illustration photography">
        <div class="project-heading">
          <div class="thumbnail">
            <img src="/assets/hospital.png" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Hospital Dom Antonio de Alvarenga</h2>
            <p class="desc"></p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article><!-- .project -->

      <article class="project project-animated photography">
        <div class="project-heading">
          <div class="thumbnail">
            <img src="/assets/Senai.png" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">SENAI</h2>
            <p class="desc"></p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article><!-- .project -->

      <article class="project project-animated illustration web animation">
        <div class="project-heading">
          <div class="thumbnail">
            <img src="/assets/basa.jpg" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Banco da Amazônia</h2>
            <p class="desc">Fóton</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article><!-- .project -->

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/cosanpa.jpg" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">COSANPA</h2>
            <p class="desc">FADESP</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/sefa.png" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">SEFA</h2>
            <p class="desc">FADESP</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/CDP.jpg" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">COMPANHIA DOCAS DO PARÁ</h2>
            <p class="desc">FADESP</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/barros.jpg" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Hospital Barros Barreto</h2>
            <p class="desc">FADESP</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/bettina.png" width="150" height="150" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <p class="meta">
            <span class="meta-like"></span>
          </p><!-- .meta -->
          <div class="title">
            <h2 class="h5">Hospital Betina Ferrus</h2>
            <p class="desc">FADESP</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/Nestle.png" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Nestlé</h2>
            <p class="desc">Dimensão Corporativa</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/batavo.jpg" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Batavo</h2>
            <p class="desc">Dimensão Corporativa</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/fadesp.png" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">FADESP</h2>
            <p class="desc">Fundação de Amparo e Desenvolvimento da Pesquisa</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/sicredi.png" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Sicredi</h2>
            <p class="desc">https://www.sicredi.com.br</p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article>

      <article class="project project-animated design">
        <div class="project-heading">
          <div class="">
            <img src="/assets/hospital.jpg" alt="Image">
          </div>
        </div><!-- .project-heading -->
        <div class="project-content">
          <div class="title">
            <h2 class="h5">Hospital Santa Marina</h2>
            <p class="desc"></p>
          </div><!-- .title -->
        </div><!-- .project-content -->
      </article><!-- .project -->
    </section><!-- #portfolio -->
  </div>
</div>

app/views/pages/_contact.html.erb
<div class="contact-switcher">

  <!-- Google Maps -->
  <div id="googlemaps" class="map-cover"></div>

  <div class="address current">
    <a href="#" class="btn to-form">Envie uma Mensagem</a>
    <div class="address-inner">
      <div class="title">
        <h2 class="h3">Onde nos Encontrar?</h2>
      </div>
      <div class="text">
        <p>A Pródiga Sistemas possui atualmente escritórios em São Paulo e Belém.</p>
      </div>
      <div class="title">
        <h4>Belém</h4>
      </div>
      <address>
        <div class="row">
          <div class="col-sm-4">
            <b>Endereço:</b>
          </div>
          <div class="col-sm-8">
            Rua Angelo Custódio,<br>
            728A, Cidade Velha,<br>
            66020-710, Belém-PA
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <b>Contato:</b>
          </div>
          <div class="col-sm-8">
            (91) 3038-8821 / (91) 3038-8824
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <b>Email:</b>
          </div>
          <div class="col-sm-8">
            <a href="mailto:contato@prodigasistemas.com.br">contato@prodigasistemas.com.br</a>
          </div>
        </div>
      </address>
      <hr>
      <div class="title">
        <h4>São Paulo</h4>
      </div>
      <address>
        <div class="row">
          <div class="col-sm-4">
            <b>Endereço:</b>
          </div>
          <div class="col-sm-8">
            Rua Cabo Romeu Casa Grande,<br />
            466, Pq. Novo Mundo,<br />
            02180-060, São Paulo-SP
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <b>Contato:</b>
          </div>
          <div class="col-sm-8">
            (91) 3038-8821 / (91) 3038-8824
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <b>Email:</b>
          </div>
          <div class="col-sm-8">
            <a href="mailto:contato@prodigasistemas.com.br">contato@prodigasistemas.com.br</a>
          </div>
        </div>
      </address>
    </div><!-- .address-inner -->
  </div><!-- .address -->
  <div class="form">
    <a href="#" class="btn to-contact">Onde nos Encontrar?</a>
    <div class="form-inner">
      <%= form_tag contacts_path, :remote => true, :authenticity_token => true, id: "contact-form", class: "form-validate" do %>

        <div class="title">
          <h2 class="h3">Enviar Mensagem</h2>
        </div>

        <div class="text">
          <p>Estamos ansiosos para receber o seu contato e poder ajudá-lo.</p>
        </div>

        <div class="row">
          <div class="col-sm-6">

            <div class="form-field">
              <div class="placeholder">
                <label for="name">Nome<span class="require">required</span></label>
                <input class="form-control" type="text" maxlength="100" name="name" id="name" minlength="2" required />
              </div>
            </div><!-- .form-field -->

          </div><!-- .col-sm-6 -->
          <div class="col-sm-6">

            <div class="form-field">
              <div class="placeholder">
                <label for="email">Email<span class="require">required</span></label>
                <input class="form-control" type="email" name="email" id="email" required />
              </div>
            </div><!-- .form-field -->

          </div><!-- .col-sm-6 -->
        </div><!-- .row -->
        <div class="form-field">
          <div class="placeholder">
            <label for="phone">Telefone<span class="require">required</span></label>
            <input class="form-control" type="text" name="phone" id="phone" required />
          </div>
        </div><!-- .form-field -->
        <div class="form-field">
          <div class="placeholder">
            <label for="message">Mesangem<span class="require">required</span></label>
            <textarea class="form-control" maxlength="5000" rows="10" name="message" id="message" required></textarea>
          </div>
        </div><!-- .form-field -->
        <div class="form-field text-right">
          <input type="submit" value="Enviar" class="btn">
        </div><!-- .form-field -->
      <% end %>
    </div><!-- .form-inner -->
  </div><!-- .form -->
</div><!-- .contact-switcher -->

app/views/pages/_gsan.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">GSAN</h4>
    </div>
    <div class="modal-body">
      <p>O Sistema Integrado de Gestão de Serviços e Saneamento (GSAN) tem como finalidade atender às necessidades das empresas e companhias de saneamento no que diz respeito à gestão comercial, financeira e de serviços. A solução integra diversas áreas como contabilidade, operacional e atendimento ao público, possibilitando ao gestor o acesso imediato a informações analíticas ou consolidadas, resultando em mais agilidade na tomada de decisões e execução dos processos de negócio.
      <br/>
      O GSAN é um software é livre e foi desenvolvido e disponibilizado pelo Ministério das Cidades, com o seguinte objetivo: "Sistema integrado de gestão de serviços de saneamento, desenvolvido com o objetivo de elevar o nível de desempenho e eficiência das empresas nacionais de abastecimento de água e coleta de esgotos." (Fonte: Portal do Software Público Brasileiro).</p>
      <p><a href="https://github.com/prodigasistemas/gsan/wiki" target="_blank" class="btn btn-default">Projeto GSAN</a></p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>

</div>

app/views/pages/_members.html.erb
<% members.each_with_index do |member, index| %> 
  <div class="col-sm-4" data-animate="flipInY">
    <div class="member">
      <div class="member-heading">
        <a class="userpic">
          <span class="btn btn-icon-user"></span>
          <%= image_tag "time/#{member[:photo]}.jpg", alt: member[:name] %>
        </a>

        <ul class="social animation animation-from-right">
          <% if member[:linkedin] %>
            <li><a href="http://br.linkedin.com/<%= member[:linkedin] %>" target="_blank" class="linkedin"></a></li>
          <% end %>
          <% if member[:twitter] %>
            <li><a href="https://twitter.com/<%= member[:twitter] %>" target="_blank" class="twitter"></a></li>
          <% end %>
          <% if member[:facebook] %>
            <li><a href="https://www.facebook.com/<%= member[:facebook] %>" target="_blank" class="facebook"></a></li>
          <% end %>
        </ul>

        <div class="title">
          <h4><%= member[:name] %></h4>
          <p><%= member[:job] %></p>
        </div>
      </div><!-- .member-heading -->
    </div><!-- .member -->
  </div><!-- .col-sm-4 -->
<% end %>

app/views/pages/_project.html.erb
<% projects.each_with_index do |project, index| %>
  <div class="col-sm-4" data-animate="flipInY">
    <div class="project">
      <div class="project-heading">
        <a class="userpic" data-toggle="modal" data-target="#<%=project[:dialog]%>">
          <span class="btn btn-icon-user"></span>
          <%= image_tag "projects/#{project[:photo]}.jpg", alt: project[:name], height: "200" %>
        </a>

        <div class="title">
          <h4><%= project[:name] %></h4>
        </div>
      </div><!-- .project-heading -->
      <!-- Modal -->
      <div class="modal fade" id="<%=project[:dialog]%>" role="dialog">
        <%= render "pages/#{project[:dialog]}" %>
      </div>
    </div><!-- .project -->
  </div><!-- .col-sm-4 -->
<% end %>

app/views/pages/_projects.html.erb
<div class="container-out container-light" id="projects">
  <div class="title title-section">
    <h2>Projetos Atuais</h2>
    <p>Esses são os projetos que o Time tem trabalhado ultimamente. </p>
    <span class="sticker">
      <i class="icon icomoon-user"></i>
    </span>
  </div><!-- .title.title-section -->
</div><!-- .container-out -->

<div class="container-out">
  <hr class="devider-heavy devider-margin-big">
  <div class="row">
    <%= render 'pages/project', projects: @projects %>
  </div>
</div><!-- .container-out -->

app/views/pages/_senaiproducao.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Controle de Produção</h4>
    </div>
    <div class="modal-body">
      <p>
      O sistema de controle de produção foi desenvolvido para atender as necessidades de gerenciamento e controle do fluxo de produção realizados pelo SENAI - Pará. Trazendo um sistema leve, com interface WEB responsiva para fácil uso por dispositivos móveis e gráficos interativos que apresentam as informações de maneira rápida para apoio a tomada de decisão.
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>

</div>

app/views/pages/_siscat.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">SISCAT</h4>
    </div>
    <div class="modal-body">
      <p>Sistema Integrado de Gerenciamento e Controle dos Terminais Mistos de Transporte Fluvial</p>
      <p><a href="http://porto.prodiga.srv.br" target="_blank" class="btn btn-default">Acesse o SISCAT</a></p>
      <p>Usuário: user@mail.com / Senha: 123456</p>
      <!-- <iframe id="iframe_container" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" width="550" height="400" src="https://prezi.com/embed/x3w_t7gn1pqm/?bgcolor=ffffff&amp;lock_to_path=0&amp;autoplay=1&amp;autohide_ctrls=0&amp;landing_data=bHVZZmNaNDBIWnNjdEVENDRhZDFNZGNIUE43MHdLNWpsdFJLb2ZHanI0U2d3S1dkUHc0RFAxZUVsdVpDOXEwZkFnPT0&amp;landing_sign=8kl-KorK5JJ3GZhi3KsNIJwKvtEKLkHilXFPaOyBi14"></iframe> -->
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>

</div>

app/views/pages/_team.html.erb
<div class="container-out container-light" id="team">
  <div class="title title-section">
    <h2>Nosso Time</h2>
    <p>Nosso maior diferencial não são as ferramentas e técnicas que utilizamos e sim as pessoas que fazem parte desse Time. </p>
    <span class="sticker">
      <i class="icon icomoon-user"></i>
    </span>
  </div><!-- .title.title-section -->
</div><!-- .container-out -->

<div class="container-out">
  <hr class="devider-heavy devider-margin-big">
  <div class="row">
    <%= render 'pages/members', members: @members %>
  </div>
</div><!-- .container-out -->

app/views/pages/_testimonial.html.erb
<div class="title title-section">
  <h2>What people say about us?</h2>
  <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.</p>
  <span class="sticker">
    <i class="icon fa fa-thumbs-o-up"></i>
  </span>
</div><!-- .title.title-section -->

<div data-animate="flipInX">
  <div class="testimonial-wrap">
    <div class="testimonial-outer">
      <ul class="testimonial" data-auto="true">
        <li>
          <div class="testimonial-content">

            <div class="text">
              <p>Imperdiet euismod bibendum orci leo cras sagittis aenean tincidunt feugiat vehicula, fringilla condimentum pharetra eu hendrerit tempor pharetra justo integer</p>
            </div>

          </div><!-- .testimonial-content  -->
          <div class="testimonial-heading">

            <div class="title">
              <h4>John Doe</h4>
              <p class="position">Microsoft</p>
            </div>

          </div><!-- .testimonial-heading  -->
        </li>
        <li>
          <div class="testimonial-content">

            <div class="text">
              <p>Sit senectus eget facilisis eu hendrerit purus consequat, adipiscing eget scelerisque mauris tempor bibendum, a netus tincidunt donec etiam luctus</p>
            </div>

          </div><!-- .testimonial-content  -->
          <div class="testimonial-heading">

            <div class="title">
              <h4>Mary Smith</h4>
              <p class="position">themeforest</p>
            </div>

          </div><!-- .testimonial-heading  -->
        </li>
        <li>
          <div class="testimonial-content">

            <div class="text">
              <p>Viverra egestas aliquam metus justo risus himenaeos nisl, cubilia vulputate diam purus taciti etiam, massa tortor est tellus sagittis lobortis</p>
            </div>

          </div><!-- .testimonial-content  -->
          <div class="testimonial-heading">

            <div class="title">
              <h4>Daniel Anderson</h4>
              <p class="position">apple</p>
            </div>

          </div><!-- .testimonial-heading  -->
        </li>
        <li>
          <div class="testimonial-content">

            <div class="text">
              <p>Porta fermentum cras dolor duis tempus enim rhoncus, orci mi pharetra curabitur augue urna, eu odio sem platea habitant ut</p>
            </div>

          </div><!-- .testimonial-content  -->
          <div class="testimonial-heading">

            <div class="title">
              <h4>Jane Johnson</h4>
              <p class="position">google</p>
            </div>

          </div><!-- .testimonial-heading  -->
        </li>
      </ul><!-- .testimonial -->
    </div><!-- .testimonial-outer -->
    <div class="testimonial-pagi"></div>
  </div><!-- .testimonial-wrap -->

</div>

app/views/pages/_uradiu.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">uRadiu</h4>
    </div>
    <div class="modal-body">
      <p>
      Um novo conceito de jukebox, com tudo que você precisa para gerenciar as músicas e os pedidos de seus clientes.
      <br/>
      Se você tem um local como bares, restaurantes, barbearias, salões de beleza, lojas, festas, ou qualquer lugar que tenha música e queira interagir de uma forma diferente com os seus clientes, o uRadiu é a solução.
      </p>
      <p><a href="http://www.uradiu.com.br" target="_blank" class="btn btn-default">uRadiu</a></p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>

</div>